name = "email-worker-auto-reply"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-12-05"

[triggers]
crons = [ "1 * * * *" ]


[observability.logs]
enabled = true
invocation_logs = false